SELECT A.AUTHOR_ID, A.AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) AS TOTAL_SALES
FROM BOOK_SALES AS BS
LEFT JOIN BOOK AS B ON BS.BOOK_ID = B.BOOK_ID
LEFT JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE SALES_DATE LIKE '2022-01%'
GROUP BY A.AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;