SELECT CASE 
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN '01' AND '03' THEN '1Q'
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN '04' AND '06' THEN '2Q'
            WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN '07' AND '09' THEN '3Q'
            ELSE '4Q'
            END AS QUARTER
            , COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER ASC;