WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR UNION ALL SELECT HOUR + 1
    FROM HOURS
    WHERE HOUR < 23
)

SELECT H.HOUR AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS AS O
RIGHT JOIN HOURS AS H
ON HOUR(O.DATETIME) = H.HOUR
GROUP BY HOUR
ORDER BY HOUR;