SELECT DISTINCT RH.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
JOIN CAR_RENTAL_COMPANY_CAR AS C
ON RH.CAR_ID = C.CAR_ID
WHERE MONTH(RH.START_DATE) = '10' AND C.CAR_TYPE = '세단'
ORDER BY CAR_ID DESC;